(env) c:\Users\79111\Desktop\python_training\GIT>py.test --alluredir allure-results test\test_add_group.py
Traceback (most recent call last):
  File "c:\users\79111\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\79111\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\79111\Desktop\python_training\GIT\env\Scripts\py.test.exe\__main__.py", line 7, in <module>
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\config\__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\config\__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\config\__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\config\__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\config\__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\users\79111\appdata\local\programs\python\python38-32\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\79111\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\allure\__init__.py", line 1, in <module>
    from allure.pytest_plugin import MASTER_HELPER
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\allure\pytest_plugin.py", line 9, in <module>
    from allure.common import AllureImpl, StepContext
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\allure\common.py", line 19, in <module>
    from allure.structure import Attach, TestStep, TestCase, TestSuite, Failure, Environment, EnvParameter
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\allure\structure.py", line 14, in <module>
    class Attach(xmlfied('attachment',
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\allure\rules.py", line 116, in xmlfied
    class MyImpl(namedlist('XMLFied', [(item[0], None) for item in items])):
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\namedlist.py", line 381, in namedlist
    type_dict = {'__init__': _make_fn('__init__', _nl_init, fields, defaults),
  File "c:\users\79111\desktop\python_training\git\env\lib\site-packages\namedlist.py", line 180, in _make_fn
    code = compile(module_node, '<string>', 'exec')
TypeError: required field "posonlyargs" missing from arguments